DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = 'dev'
    ) THEN
        CREATE USER dev WITH PASSWORD 'devpassword';
    END IF;

    GRANT CONNECT ON DATABASE postgres TO dev;
    GRANT USAGE ON SCHEMA public TO dev;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dev;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dev;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dev;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO dev;
END;
$$;

DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = 'hrmanagerapp'
    ) THEN
        CREATE USER HrManagerApp WITH PASSWORD 'HrManagerPassword';
    END IF;

    GRANT CONNECT ON DATABASE postgres TO HrManagerApp;
    GRANT USAGE ON SCHEMA public TO HrManagerApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO HrManagerApp;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO HrManagerApp;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO HrManagerApp;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO HrManagerApp;
END;
$$;
